name: urban_quest
description: "A mobile app for urban exploration through gamification"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase - versiones específicas compatibles
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1

  # Google Maps
  google_maps_flutter: ^2.5.0

  flutter_map: ^7.0.2
  latlong2: ^0.9.1


  # Geolocalización
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

  # State Management
  provider: ^6.1.2

  # Utilidades
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.8

  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  

  # Assets (para tus POIs y rutas en JSON)
  assets:
    - assets/data/
    - assets/images/
