// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOyxlJ-ZG_pyVf-cOX-2wW13_WPUxPGDM',
    appId: '1:194784821170:web:5af4fe8607b0847d11eeab',
    messagingSenderId: '194784821170',
    projectId: 'urbanquest-polimi',
    authDomain: 'urbanquest-polimi.firebaseapp.com',
    storageBucket: 'urbanquest-polimi.firebasestorage.app',
    measurementId: 'G-Z94DBEX85E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCplowyTjNVh46WxHJZolCevcJUEghDgnE',
    appId: '1:194784821170:android:8a63f94cd249a19311eeab',
    messagingSenderId: '194784821170',
    projectId: 'urbanquest-polimi',
    storageBucket: 'urbanquest-polimi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcTAP2eppQ-A2pT1V_KEHFKyjXwWTIcyU',
    appId: '1:194784821170:ios:4c46f9e3b6a2d85b11eeab',
    messagingSenderId: '194784821170',
    projectId: 'urbanquest-polimi',
    storageBucket: 'urbanquest-polimi.firebasestorage.app',
    iosBundleId: 'com.example.urbanQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcTAP2eppQ-A2pT1V_KEHFKyjXwWTIcyU',
    appId: '1:194784821170:ios:4c46f9e3b6a2d85b11eeab',
    messagingSenderId: '194784821170',
    projectId: 'urbanquest-polimi',
    storageBucket: 'urbanquest-polimi.firebasestorage.app',
    iosBundleId: 'com.example.urbanQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOyxlJ-ZG_pyVf-cOX-2wW13_WPUxPGDM',
    appId: '1:194784821170:web:88d8c73f1bd6984211eeab',
    messagingSenderId: '194784821170',
    projectId: 'urbanquest-polimi',
    authDomain: 'urbanquest-polimi.firebaseapp.com',
    storageBucket: 'urbanquest-polimi.firebasestorage.app',
    measurementId: 'G-W5234M6ETY',
  );
}
